name: AWS Tests

on: push

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: List s3 buckets
        run: aws s3 ls
